CREATE DATABASE IF NOT EXISTS TicketBurst;
USE TicketBurst;

CREATE TABLE IF NOT EXISTS USUARIOS (
    CORREO VARCHAR(320) PRIMARY KEY,
    USERNAME VARCHAR(16) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    HABILITADO BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS ORGANIZADORES (
    ID_ORGANIZADOR INT PRIMARY KEY,
    NOMBRE VARCHAR(128) NOT NULL UNIQUE,
    DIRECCION VARCHAR(256) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL,
    CORREO VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    IDENTIFICADOR_FISCAL INT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EVENTOS (
    ID_EVENTO INT PRIMARY KEY,
    TITULO VARCHAR(40) NOT NULL,
    DESCRIPCION VARCHAR(512) NOT NULL,
    ARTISTAS VARCHAR(256) NOT NULL,
    PROVINCIA VARCHAR(64) NOT NULL,
    CARTEL_RUTA VARCHAR(512) NOT NULL,
    MAPA_RUTA VARCHAR(512) NOT NULL,
    UBICACION VARCHAR(256) NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    HORA_VENTA_TICKETS DATETIME NOT NULL,
    ID_ORGANIZADOR INT NOT NULL,
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADORES (ID_ORGANIZADOR)
);

CREATE TABLE IF NOT EXISTS TICKETS (
    ID_TICKET INT ,
    ID_EVENTO INT,
    NOMBRE_ZONA VARCHAR(32) NOT NULL,
    PISTA BOOLEAN NOT NULL,
    CORREO_USER VARCHAR(320) NOT NULL,
    COLUMNA_INTERNA INT NOT NULL,
    FILA_INTERNA INT NOT NULL,
    DIRECCION_REAL VARCHAR(255) NOT NULL,
    PRECIO_TICKET DOUBLE NOT NULL,
    PRIMARY KEY (ID_TICKET,ID_EVENTO),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
    FOREIGN KEY (CORREO_USER) REFERENCES USUARIOS(CORREO)
);

CREATE TABLE IF NOT EXISTS COMPRAS (
    CORREO VARCHAR(320),
    ID_TICKET INT,
    ID_EVENTO INT,
    DNI_COMPRADOR VARCHAR(9) NOT NULL,
    PRIMARY KEY(ID_TICKET, CORREO),
    FOREIGN KEY (CORREO) REFERENCES USUARIOS(CORREO),
    FOREIGN KEY (ID_TICKET,ID_EVENTO) REFERENCES TICKETS(ID_TICKET,ID_EVENTO)
);