version: '3'
services:
  back1:
    build: ./Back
    ports:
      - "3001:3000"
  back2:
    build: ./Back
    ports:
      - "3002:3000"
  database:
    build: ./DB
    ports:
      - "3306:3306"
  proxy:
    build: ./Proxy
    ports:
      - "80:80"
      - "443:443"